server:
  port: 8088

spring:
  application:
    name: springcloud-config

  #####################SVN#############################
  profiles:
    active: subversion
  #####################SVN#############################

  cloud:
    config:
      server:
        native:
          search-locations: C://WorkPlace-Project//AgricultureProject//ConfigFiles
        git:
          uri: https://github.com/dawei1980/ConfigCenter  #git仓库地址，就是刚才创建的git仓库
          #配置GitHub的账号和密码
          username: unicloud2020
          password: birancloud2020
          skipSslValidation: true #跳过SSL的认证
          force-pull: true
          #配置GitHub的仓库的搜索路径（固定的不要补全！！！）
          search-paths: ConfigCenter

eureka:
  client:
    service-url:
      #defaultZone 这个是不会提示的，此处需要自己写
      #实际上属性应该是service-url,这个属性是个map（key-value）格式；当key是defaultZone的时候才能被解析；所以这里没有提示，
      #但是自己还需要写一个defaultZone；
      defaultZone: http://localhost:8761/eureka/eureka
