server:
  port: 8083

spring:
  application:
    name: spring-login
  cloud:
    config:
      uri: http://localhost:8082/ConfigCenterDev #config server 端地址
      profile: dev #项目配置文件选择
      label: master #git仓库的分支
      discovery:
        enabled: true
        service-id: springcloud-config #config-server服务名称

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      #defaultZone 这个是不会提示的，此处需要自己写
      #实际上属性应该是service-url,这个属性是个map（key-value）格式；当key是defaultZone的时候才能被解析；所以这里没有提示，
      #但是自己还需要写一个defaultZone；
      defaultZone: http://localhost:8761/eureka/eureka
